baseURL = "http://kb.altinity.com/"
languageCode = "en-us"
title = "Altinity® Knowledge Base for ClickHouse®"
# theme = ["docsy"]
publishDir = "docs"
enableRobotsTXT = true

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true


# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "UA-00000000-0"
# id = "UA-101676615-2"

# Language configuration

[languages]
[languages.en]
title = "Altinity® Knowledge Base for ClickHouse®"
description = "Altinity® Knowledge Base for ClickHouse®"
languageName = "English"
# Weight used for sorting.
weight = 1
time_format_default = "2006.01.02"
time_format_blog = "2006.01.02"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"

# Everything below this are Site Params

[params]
# copyright = " Altinity Inc."
copyright = " Altinity Inc. Altinity®, Altinity.Cloud®, and Altinity Stable® are registered trademarks of Altinity, Inc. ClickHouse® is a registered trademark of ClickHouse, Inc.; Altinity is not affiliated with or associated with ClickHouse, Inc. Kafka, Kubernetes, MySQL, and PostgreSQL are trademarks and property of their respective owners."
privacy_policy = "https://altinity.com/privacy-policy/"
favicon = "/favicon.ico"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the 
# current doc set.
version = "0.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://kb.altinity.com"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/Altinity/altinityknowledgebase"
github_branch = "main"


# An optional link to a related project repo. For example, the sibling repository where your product code lives.
# github_project_repo = "https://github.com/orgs/Altinity/dashboard"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "011737558837375720776:fsdu1nryfng"
# gcs_engine_id = "e40ddbbd000474052" <-- fosforus

# gcs_engine_id = "8babf5c6d74f8777e"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = true

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = true

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
# enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
# yes = 'Glad to hear it! Please <a href="https://github.com/johnhummelAltinity/johnhummelAltinity.github.io/issues/new">tell us how we can improve</a>.'
# no = 'Sorry to hear that. Please <a href="https://github.com/johnhummelAltinity/johnhummelAltinity.github.io/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.developer]]
  name ="Slack"
  url = "https://altinity.com/slack"
  icon = "fab fa-slack"
  desc = "Join our Slack Community"
[[params.links.developer]]
	name ="X"
	url = "https://twitter.com/AltinityDB"
	icon = "fab fa-twitter"
  desc = "Follow us on X to get the latest news!"
[[params.links.developer]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/company/altinity/"
  icon = "fab fa-linkedin"
        desc = "Partner with us on LinkedIn."
[[params.links.developer]]
	name = "Youtube"
	url = "https://www.youtube.com/channel/UCE3Y2lDKl_ZfjaCrh62onYA"
	icon = "fab fa-youtube"
        desc = "Watch our videos."
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/orgs/Altinity/"
	icon = "fab fa-github"
  desc = "Development takes place here!"
[[params.links.developer]]
  name = "Reddit"
  url = "https://www.reddit.com/r/Clickhouse/"
  icon = "fab fa-reddit"
  desc = "Altinity on Reddit"
[outputFormats]
[outputFormats.PRINT]
baseName = "index"
isHTML = true
mediaType = "text/html"
path = "printview"
permalinkable = false

# Controls the ability to print.
[outputs]
#home = ["HTML", "print"]
section = [ "HTML", "print"]
#page = ["HTML", "print"]

[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/google/docsy"
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
